import express from 'express';
import { forgotPassword, login, logout, register, resetPassword, verifyOtp, } from '../controllers/auth.controller';
const router = express.Router();
router.post('/register', register);
router.post('/verify-otp', verifyOtp);
router.post('/login', login);
router.post('/forgot-password', forgotPassword);
router.put('/reset-password/:token', resetPassword);
router.post('/logout', logout);
export default router;
